export const FSQUARE_CLIENT_ID = "ZM15PQ4WAGDP2I50CO1BRFTW4XBHR21CGE2TCZPKZTE0NKZC";
export const FSQUARE_CLIENT_SECRET = "WTKJKRTBJTHNAUDSF3BL1BBEN5PN23RZQKIOXPLGF1RKXQZH";
export const GOOGLE_MAPS_KEY = "AIzaSyARdvlX22a92EHzv5rAZeC-q2uDOQhQtkI";
